version: '2'
services:
  oto-frontend:
    image: 'otomato/oto-front:7'
    links: 
     - otoprod
    ports:
     - 3000
  otoprod:
    image: 'antweiss/oto-products:7'
    ports:
     - 5000
    links:
     - mongo
  spring-orders:
    image: 'otomato/oto-orders:4'
    links:
     - mongo
    ports:
     - 8080
  mongo:
    image: mongo

