apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: otofrontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: otofrontend
    spec:
      containers:
      - name: otofront
        image: antweiss/otofrontend:master
        ports:
        - containerPort: 3000
